// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/demo-login": {
            "post": {
                "description": "使用手机号 + 角色(supplier/client) 直接获取外部 JWT（不会发送验证码）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Demo 手机号登录（仅测试用）",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.DemoLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.DemoLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/send-code": {
            "post": {
                "description": "向手机号发送登录/注册验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "发送验证码",
                "parameters": [
                    {
                        "description": "手机号",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SendCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.SendCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verify-code": {
            "post": {
                "description": "通过手机号和验证码进行登录，若手机号未注册则自动注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "验证码登录/注册",
                "parameters": [
                    {
                        "description": "手机号和验证码",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.VerifyCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.VerifyCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/wechat-login": {
            "post": {
                "description": "用前端临时 code 换取 openid，再查询内部系统中该 openid 绑定的供应商信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "微信小程序登录",
                "parameters": [
                    {
                        "description": "微信登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.WechatLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.WechatLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/client/profile": {
            "get": {
                "description": "获取当前登录 client 的档案信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "获取客户档案",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.ClientProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建或更新当前登录 client 的公司信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "创建或更新客户档案",
                "parameters": [
                    {
                        "description": "客户档案信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.CreateClientProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.ClientProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy/supplier/bind-wechat": {
            "post": {
                "description": "验证供应商身份并绑定 OpenId，成功后 isSucceed=true",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "微信端绑定供应商",
                "parameters": [
                    {
                        "description": "绑定参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.BindWeChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.BindWeChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/proxy.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy/supplier/get-by-wechat": {
            "post": {
                "description": "data 有数据=已绑定供应商；data 为空数组=未绑定；isSucceed=false 看 message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "根据 Openid 获取供应商信息",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.GetByWeChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.GetByWeChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/proxy.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy/supplier/inquiry-detail": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "供应商查看采购需求详情及报价情况",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.InquiryDetailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.InquiryDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/proxy.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy/supplier/inquiry-query": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "查询供应商可报价的招标信息",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.InquiryQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.InquiryQueryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/proxy.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy/supplier/inquiry-quoted": {
            "post": {
                "description": "返回该供应商已提交过报价的询价单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "查询供应商已报价的采购单",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.InquiryBySupplierQuotedRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.InquiryBySupplierQuotedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/proxy.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy/supplier/quote-delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "撤回或删除供应商报价",
                "parameters": [
                    {
                        "description": "操作参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.QuoteDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.QuoteDeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/proxy.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/proxy/supplier/quote-save": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "summary": "供应商提交或保存报价",
                "parameters": [
                    {
                        "description": "报价参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.QuoteSaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.QuoteSaveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/proxy.BaseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/supplier/capabilities": {
            "post": {
                "description": "更新供应商的机器设备数量（增量更新）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supplier"
                ],
                "summary": "更新机器能力",
                "parameters": [
                    {
                        "description": "机器能力信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/supplier.UpdateCapabilitiesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/supplier.CapabilitiesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/supplier.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/supplier/full-info": {
            "get": {
                "description": "获取供应商的企业信息、资质和生产能力",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supplier"
                ],
                "summary": "获取供应商完整信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/supplier.SupplierFullInfoResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/supplier/profile": {
            "get": {
                "description": "获取当前用户的供应商档案信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supplier"
                ],
                "summary": "获取供应商档案",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/supplier.SupplierProfileResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/supplier.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建或更新供应商的企业信息和机器能力",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supplier"
                ],
                "summary": "创建/更新供应商档案",
                "parameters": [
                    {
                        "description": "供应商信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/supplier.CreateSupplierRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/supplier.SupplierProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/supplier.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.DemoLoginRequest": {
            "type": "object",
            "required": [
                "phone",
                "role"
            ],
            "properties": {
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "supplier",
                        "client"
                    ]
                }
            }
        },
        "auth.DemoLoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "isNew": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "auth.SendCodeRequest": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        },
        "auth.SendCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "auth.VerifyCodeRequest": {
            "type": "object",
            "required": [
                "code",
                "phone"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "auth.VerifyCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "isNewUser": {
                    "description": "是否新用户（首次注册）",
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.WechatLoginData": {
            "type": "object",
            "properties": {
                "isBound": {
                    "type": "boolean"
                },
                "openId": {
                    "type": "string"
                },
                "supplierInfo": {
                    "description": "内部系统 BC_Customer_GetByWeChat 返回的 data 数组，未绑定时为 []"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.WechatLoginRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "userInfo": {}
            }
        },
        "auth.WechatLoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/auth.WechatLoginData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "client.ClientProfile": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "companyName": {
                    "type": "string"
                },
                "contactName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "description": "equals users.id",
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "description": "equals ID, kept for clarity",
                    "type": "string"
                }
            }
        },
        "client.ClientProfileResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/client.ClientProfile"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "client.CreateClientProfileRequest": {
            "type": "object",
            "required": [
                "address",
                "companyName",
                "contactName",
                "industry"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "companyName": {
                    "type": "string"
                },
                "contactName": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                }
            }
        },
        "client.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "proxy.BaseResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "outData": {},
                "statusCode": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "proxy.BindWeChatOutData": {
            "type": "object",
            "properties": {
                "intRetVal": {
                    "type": "integer"
                },
                "strMessage": {
                    "type": "string"
                }
            }
        },
        "proxy.BindWeChatRequest": {
            "type": "object",
            "properties": {
                "CustomerCode": {
                    "type": "string",
                    "example": "PD0201"
                },
                "Mobile": {
                    "type": "string",
                    "example": "13800138000"
                },
                "Openid": {
                    "type": "string",
                    "example": "oXxx123abc"
                },
                "Type": {
                    "description": "0:公众号 1:小程序",
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "proxy.BindWeChatResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "TODO: 待补充"
                },
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "outData": {
                    "$ref": "#/definitions/proxy.BindWeChatOutData"
                },
                "statusCode": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "proxy.GetByWeChatOutData": {
            "type": "object",
            "properties": {
                "intRetVal": {
                    "type": "integer"
                }
            }
        },
        "proxy.GetByWeChatRequest": {
            "type": "object",
            "properties": {
                "Openid": {
                    "type": "string",
                    "example": "oXxx123abc"
                },
                "Type": {
                    "description": "0:公众号 1:小程序",
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "proxy.GetByWeChatResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "TODO: 待补充（空数组=未绑定，有数据=已绑定）"
                },
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "outData": {
                    "$ref": "#/definitions/proxy.GetByWeChatOutData"
                },
                "statusCode": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "proxy.InquiryBySupplierQuotedRequest": {
            "type": "object",
            "properties": {
                "Supplier": {
                    "type": "string",
                    "example": "C001"
                }
            }
        },
        "proxy.InquiryBySupplierQuotedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "outData": {},
                "statusCode": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "proxy.InquiryDetailOutData": {
            "type": "object",
            "properties": {
                "strMessage": {
                    "type": "string"
                }
            }
        },
        "proxy.InquiryDetailRequest": {
            "type": "object",
            "properties": {
                "InquiryId": {
                    "type": "string",
                    "example": "INQ-2024-001"
                },
                "Supplier": {
                    "type": "string",
                    "example": "C001"
                }
            }
        },
        "proxy.InquiryDetailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "TODO: 待补充"
                },
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "outData": {
                    "$ref": "#/definitions/proxy.InquiryDetailOutData"
                },
                "statusCode": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "proxy.InquiryQueryRequest": {
            "type": "object",
            "properties": {
                "BeginDate": {
                    "description": "发布开始时间，可选",
                    "type": "string",
                    "example": ""
                },
                "EndDate": {
                    "description": "发布结束时间，可选",
                    "type": "string",
                    "example": ""
                },
                "IncludeEnd": {
                    "description": "是否包含已截止 1:包含 0:不包含",
                    "type": "string",
                    "example": "0"
                },
                "P_chnName": {
                    "description": "产品名称，模糊查询，可选",
                    "type": "string",
                    "example": ""
                },
                "Supplier": {
                    "type": "string",
                    "example": "C001"
                }
            }
        },
        "proxy.InquiryQueryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "TODO: 待补充"
                },
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "outData": {},
                "statusCode": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "proxy.QuoteDeleteOutData": {
            "type": "object",
            "properties": {
                "strMessage": {
                    "type": "string"
                }
            }
        },
        "proxy.QuoteDeleteRequest": {
            "type": "object",
            "properties": {
                "OperateType": {
                    "description": "Cancel:撤回 Delete:删除",
                    "type": "string",
                    "example": "Cancel"
                },
                "QuoteId": {
                    "type": "string",
                    "example": "QT-2024-001"
                },
                "Supplier": {
                    "type": "string",
                    "example": "C001"
                }
            }
        },
        "proxy.QuoteDeleteResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "TODO: 待补充"
                },
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "outData": {
                    "$ref": "#/definitions/proxy.QuoteDeleteOutData"
                },
                "statusCode": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "proxy.QuoteSaveOutData": {
            "type": "object",
            "properties": {
                "ReturnId": {
                    "type": "string"
                },
                "strMessage": {
                    "type": "string"
                }
            }
        },
        "proxy.QuoteSaveRequest": {
            "type": "object",
            "properties": {
                "Id": {
                    "description": "空=新增",
                    "type": "string",
                    "example": ""
                },
                "InquiryId": {
                    "type": "string",
                    "example": "INQ-2024-001"
                },
                "LeadDays": {
                    "type": "integer",
                    "example": 7
                },
                "LeadTimeStartDate": {
                    "type": "string",
                    "example": "1"
                },
                "Payment": {
                    "type": "string",
                    "example": "货到付款"
                },
                "Price": {
                    "type": "string",
                    "example": "13.00"
                },
                "QStatus": {
                    "description": "0:草稿 1:已撤回 2:已提交",
                    "type": "string",
                    "example": "0"
                },
                "QuoteJson": {
                    "type": "string",
                    "example": ""
                },
                "Remark": {
                    "type": "string",
                    "example": ""
                },
                "StockStatus": {
                    "type": "string",
                    "example": "1"
                },
                "Supplier": {
                    "type": "string",
                    "example": "C001"
                },
                "TaxRate": {
                    "type": "string",
                    "example": "0.13"
                },
                "Unit": {
                    "type": "string",
                    "example": "个"
                },
                "isShipping": {
                    "type": "string",
                    "example": "1"
                },
                "isTax": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "proxy.QuoteSaveResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "TODO: 待补充"
                },
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "outData": {
                    "$ref": "#/definitions/proxy.QuoteSaveOutData"
                },
                "statusCode": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "supplier.CapabilitiesResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "supplier.CreateSupplierRequest": {
            "type": "object",
            "required": [
                "companyName",
                "companyType"
            ],
            "properties": {
                "capabilities": {
                    "description": "机器能力 {a:1, b:2}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "companyName": {
                    "type": "string"
                },
                "companyType": {
                    "type": "string"
                }
            }
        },
        "supplier.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "supplier.SupplierFullInfo": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "description": "生产能力",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "info": {
                    "description": "企业信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/supplier.SupplierInfo"
                        }
                    ]
                },
                "qualification": {
                    "description": "资质信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/supplier.SupplierQualification"
                        }
                    ]
                }
            }
        },
        "supplier.SupplierFullInfoResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/supplier.SupplierFullInfo"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "supplier.SupplierInfo": {
            "type": "object",
            "properties": {
                "companyName": {
                    "type": "string"
                },
                "companyType": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "supplier.SupplierProfile": {
            "type": "object",
            "properties": {
                "companyName": {
                    "description": "企业名称",
                    "type": "string"
                },
                "companyType": {
                    "description": "企业类型",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "description": "equals users.id",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "description": "关联用户，唯一索引",
                    "type": "string"
                }
            }
        },
        "supplier.SupplierProfileResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/supplier.SupplierProfile"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "supplier.SupplierQualification": {
            "type": "object"
        },
        "supplier.UpdateCapabilitiesRequest": {
            "type": "object",
            "required": [
                "capabilities"
            ],
            "properties": {
                "capabilities": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Fantasy Bounty API",
	Description:      "fantasy对外",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
